server:
  servlet:
    context-path: /uaa
spring:
  datasource:
    url: jdbc:mysql://192.168.30.131:3306/user_db?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root