@startuml

UsernamePasswordAuthenticationFilter -> AbstractAuthenticationProcessingFilter : doFilter()

AbstractAuthenticationProcessingFilter -> UsernamePasswordAuthenticationFilter : attemptAuthentication()

UsernamePasswordAuthenticationFilter -> ProviderManager : authenticate()

ProviderManager -> AuthenticationProvider : authenticate()



@enduml