server:
  servlet:
    context-path: /uaa
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


ignored:
  urls:
    - /r/r3